const fs=require('fs'),path=require('path'),c=require('../home-copy/node_modules/cheerio'),{transformHTML}=require('./content.cjs');const m=require('../../site-copy-manifest.json'),dict=require('./translations.json'),edits=require('./editorial.cjs');Object.assign(dict,edits);
const replacements=[[/北京(?:英創|盈創|盈创|英创|銀創|銀创)(?:天迪|天地)(?:科技|技術|テクノロジー)(?:有限公司|有限会社)/g,'北京盈創天地科技有限公司'],[/英創天地|英創天迪|盈创天地/g,'盈創天地'],[/デジタルマイニング/g,'データ収集'],[/ブラインドパネル|ブラインドボード/g,'ブラインドプレート'],[/特別な運用|特殊作戦/g,'特殊作業'],[/自己組織化ネットワーク|自己組織型ネットワーク/g,'アドホックネットワーク']];
for(const [s,t]of Object.entries(dict)){let v=t;for(const [r,to]of replacements)v=v.replace(r,to);dict[s]=v}
const names=Object.keys(edits).sort((a,b)=>b.length-a.length);for(const [s,t]of Object.entries(dict)){if(s.includes(' - 北京盈创天地科技有限公司')){const prefix=s.split(' - ')[0];if(dict[prefix])dict[s]=dict[prefix]+' | 北京盈創天地科技有限公司'}}
function translate(s){const t=s.trim();return Object.hasOwn(dict,t)?s.slice(0,s.indexOf(t))+dict[t]+s.slice(s.indexOf(t)+t.length):s}
for(const p of m.pages){const original=fs.readFileSync(path.join(__dirname,'source',p.file),'utf8');const dom=c.load(transformHTML(original,translate));dom('html').attr('lang','ja');dom('meta[property="og:locale"]').attr('content','ja_JP');const base=path.posix.relative(path.posix.dirname(p.file),'site-assets')||'.';dom('head').append(`<link rel="stylesheet" href="${base}/japanese.css"><script defer src="${base}/japanese.js"></script>`);fs.writeFileSync(p.file,dom.html())}
fs.writeFileSync('site-assets/japanese.js',`/* Translate late-rendered source widgets without modifying their identifiers. */\n(()=>{const dictionary=${JSON.stringify(dict)},translate=s=>{const key=s.trim();if(!Object.hasOwn(dictionary,key))return s;return s.slice(0,s.indexOf(key))+dictionary[key]+s.slice(s.indexOf(key)+key.length)};function visit(node){if(node.nodeType===3){if(node.parentElement?.closest('script,style,textarea,code'))return;const value=translate(node.nodeValue);if(value!==node.nodeValue)node.nodeValue=value;return}if(node.nodeType!==1)return;for(const attr of ['title','alt','placeholder','aria-label'])if(node.hasAttribute(attr)){const text=node.getAttribute(attr),value=translate(text);if(value!==text)node.setAttribute(attr,value)}for(const child of node.childNodes)visit(child)}document.documentElement.lang='ja';const start=()=>{visit(document.body);new MutationObserver(records=>{for(const r of records){if(r.type==='characterData')visit(r.target);else for(const n of r.addedNodes)visit(n)}}).observe(document.body,{subtree:true,childList:true,characterData:true})};if(document.body)start();else document.addEventListener('DOMContentLoaded',start);})();`);
fs.writeFileSync('site-assets/japanese.css',`html[lang="ja"] body{font-family:"Yu Gothic","Hiragino Kaku Gothic ProN",Meiryo,Arial,sans-serif}html[lang="ja"] .J_nav_item_name,html[lang="ja"] .nav_item_name{white-space:nowrap}html[lang="ja"] .tabButtonText{line-height:1.5;white-space:normal;word-break:normal}html[lang="ja"] .J_floatBtnText{white-space:nowrap}html[lang="ja"] .newsDetailContent,html[lang="ja"] .detailedDesc{line-height:1.8;overflow-wrap:break-word}html[lang="ja"] .fk-productName{white-space:normal;overflow-wrap:break-word}\n`);
for(const f of fs.readdirSync('.').filter(f=>f.endsWith('.html')&&!m.pages.some(p=>p.file===f))){let s=fs.readFileSync(f,'utf8');s=s.replace('lang="zh-CN"','lang="ja"').replaceAll('北京盈创天地科技有限公司','北京盈創天地科技有限公司').replaceAll('进入页面','ページを開く');fs.writeFileSync(f,s)}
fs.writeFileSync(path.join(__dirname,'final-translations.json'),JSON.stringify(dict,null,2));console.log('Applied Japanese to',m.pages.length,'pages; dictionary',Object.keys(dict).length);
