const cheerio=require('../home-copy/node_modules/cheerio'),acorn=require('../home-copy/node_modules/acorn');
const han=/[\u3400-\u9fff]/;const visibleAttrs=['title','alt','placeholder','aria-label'];
function plain(s){return typeof s==='string'&&han.test(s)&&!/^\s*(?:https?:|\/\/|javascript:|data:)/.test(s)&&!s.includes('fontface__')&&!/^\s*(?:[.#][\w-]+\s*\{|font-family:)/.test(s)}
const technicalKeys=new Set(['substring','fontFamily','ff','fontName','family','fontfamily']);
function walkJson(value,fn){if(typeof value==='string')return transformString(value,fn);if(Array.isArray(value))return value.map(v=>walkJson(v,fn));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,technicalKeys.has(k)?v:walkJson(v,fn)]));return value}
function transformString(s,fn){if(!plain(s))return s;const t=s.trim();if((t[0]==='{'||t[0]==='[')&&t.length>20){try{return JSON.stringify(walkJson(JSON.parse(t),fn))}catch{}}if(/<\/?[a-z][^>]*>/i.test(s)){return transformHTML(s,fn,false)}if(/(?:function\s*\(|return false;|\$\(|document\.)/.test(s))return s;return fn(s)}
function transformScript(code,fn){const changes=[];try{const ast=acorn.parse(code,{ecmaVersion:'latest',allowReturnOutsideFunction:true});function walk(n,parent,key){if(!n||typeof n!=='object')return;if(parent?.type==='Property'&&technicalKeys.has(parent.key?.name||parent.key?.value))return;if(n.type==='Literal'&&typeof n.value==='string'&&!(parent?.type==='Property'&&key==='key')){const value=transformString(n.value,fn);if(value!==n.value)changes.push([n.start,n.end,JSON.stringify(value)]);return}for(const [k,v]of Object.entries(n)){if(Array.isArray(v))v.forEach(x=>walk(x,n,k));else if(v&&typeof v==='object')walk(v,n,k)}}walk(ast);for(const [a,b,v]of changes.sort((x,y)=>y[0]-x[0]))code=code.slice(0,a)+v+code.slice(b)}catch{}return code}
function transformHTML(html,fn,document=true){const dom=cheerio.load(html,{decodeEntities:false},document);function visit(n){if(n.type==='text'){if(!['script','style'].includes(n.parent?.name)&&plain(n.data))n.data=fn(n.data);return}if(n.type==='script'){if(!n.attribs?.src)dom(n).text(transformScript(dom(n).html()||'',fn));return}if(n.type==='comment'||n.type==='style')return;if(n.attribs){for(const a of visibleAttrs)if(plain(n.attribs[a]))n.attribs[a]=fn(n.attribs[a]);if(n.name==='meta'&&['description','keywords','og:title','og:description','twitter:title','twitter:description','name'].includes(n.attribs.name||n.attribs.property||n.attribs.itemprop)&&plain(n.attribs.content))n.attribs.content=fn(n.attribs.content);if(n.name==='input'&&['button','submit'].includes(n.attribs.type)&&plain(n.attribs.value))n.attribs.value=fn(n.attribs.value)}for(const child of n.children||[])visit(child)}visit(dom.root()[0]);return document?dom.html():dom.root().html()}
module.exports={plain,transformHTML,transformScript};
