const fs=require('fs'),path=require('path'),cheerio=require('cheerio');const m=require('../../site-copy-manifest.json'),route=Object.fromEntries(m.pages.map(p=>[p.url,p.file])),tabs={};
for(const p of m.pages){if(!p.url.includes('_reqArgs'))continue;const d=JSON.parse(new URL(p.url).searchParams.get('_reqArgs'));const key=Object.keys(d.args).find(k=>/^m\d+pageno$/.test(k));if(!key)continue;const module=key.match(/m(\d+)/)[1],dom=cheerio.load(fs.readFileSync(p.file,'utf8'));dom('[id^="formTabContent"]').each((_,e)=>dom(e).children().each((i,child)=>{if(dom(child).find('#productList'+module+',#module'+module).length)tabs[p.file]={id:dom(e).attr('id').replace('Content','ButtonList'),index:i}}))}
fs.writeFileSync('site-assets/local-navigation.js',`/* Original site UI, with local routes for static hosting. */
(()=>{const root=new URL('../',document.currentScript.src),routes=${JSON.stringify(route)},tabs=${JSON.stringify(tabs)};
function normalize(value){try{const u=new URL(value,'https://yinchung.com');u.hash='';if(u.hostname==='www.yinchung.com')u.hostname='yinchung.com';if(u.hostname==='yinchung.com')u.protocol='https:';if(u.pathname==='/index.jsp'||u.pathname==='/index.html')u.pathname='/';if(u.pathname==='/col.jsp'&&u.searchParams.has('id')){u.pathname='/h-col-'+u.searchParams.get('id')+'.html';u.searchParams.delete('id')}if(u.searchParams.has('_reqArgs')){const d=JSON.parse(u.searchParams.get('_reqArgs'));d.args=Object.fromEntries(Object.entries(d.args).sort(([a],[b])=>a.localeCompare(b)));u.searchParams.set('_reqArgs',JSON.stringify(d))}return u.href}catch{return ''}}
document.addEventListener('click',event=>{const a=event.target.closest('a');if(!a)return;const href=a.getAttribute('href')||'';let value=href,hash='';if(href.startsWith('javascript:')){if(!href.includes('jumpToModulePosition'))return;value=href.match(/['"]([^'"]+\\.html)['"]/)?.[1];hash='#module'+(href.match(/jumpToModulePosition\\((\\d+)/)?.[1]||'');if(!value)return}else{let u;try{u=new URL(href,location.href)}catch{return}hash=u.hash;if(u.origin===location.origin){if(!u.searchParams.has('_reqArgs'))return;value='https://yinchung.com'+u.pathname+u.search}else value=u.href}const f=routes[normalize(value)];if(f){event.preventDefault();event.stopImmediatePropagation();location.href=new URL(f,root).href+hash}},true);
window.addEventListener('load',()=>{const t=tabs[location.pathname.split('/').pop()];if(t&&t.index)document.querySelector('#'+t.id+' .j_tabitem_'+t.index)?.click();if(location.hash.startsWith('#module'))document.getElementById(location.hash.slice(1))?.scrollIntoView()});})();`);
const aliases={'index_cn.html':'index.html','product.html':'h-col-103.html','product_cn.html':'h-col-103.html','solution.html':'h-col-137.html','solution_cn.html':'h-col-137.html','news.html':'h-col-132.html','news_cn.html':'h-col-132.html','company.html':'h-col-101.html','company_cn.html':'h-col-101.html','contact.html':'h-col-101.html#module617','contact_cn.html':'h-col-101.html#module617','product-dr600.html':'sys-pd/51.html','product-dr600_cn.html':'sys-pd/51.html'};
for(const [f,target]of Object.entries(aliases))fs.writeFileSync(f,`<!DOCTYPE html><html lang="zh-CN"><head><meta charset="utf-8"><meta http-equiv="refresh" content="0;url=${target}"><title>北京盈创天地科技有限公司</title></head><body><a href="${target}">进入页面</a></body></html>`);
fs.writeFileSync('SITE-COPY.md',`# 母公司网站原样副本\n\n来源：https://yinchung.com/\n复制时间：${m.copiedAt}\n\n共 ${m.pages.length} 个可由站内公开链接发现的页面，${m.assets.length} 项本地资源。首页为 index.html。保留源站的文字、品牌、图片、布局与脚本；站内链接和分页适配本地静态文件。旧 dongying 栏目地址跳转到对应原版页面。\n\n源站在线服务（地图、统计、表单提交等）仍依赖其服务端，不包含后台程序或管理数据。源站无法下载的资源见 site-copy-manifest.json 的 errors；保留原链接，由浏览器按源站逻辑回退。\n`);
console.log('Local navigation and existing entry points ready.');
