const fs=require('fs'),path=require('path'),crypto=require('crypto'),cheerio=require('cheerio');
const origin='https://yinchung.com',root=process.cwd(),raw=path.join(__dirname,'raw');fs.mkdirSync(raw,{recursive:true});
const pages=new Map(),assets=new Map(),errors=[],queue=[origin+'/'],scheduled=new Set(queue);const hash=s=>crypto.createHash('sha256').update(s).digest('hex').slice(0,16);
function norm(s,base=origin){try{const u=new URL(s.replace(/&amp;|&#x26;/g,'&'),base);u.hash='';if(u.hostname==='www.yinchung.com')u.hostname='yinchung.com';if(u.hostname==='yinchung.com')u.protocol='https:';if(u.origin===origin){if(u.pathname==='/index.jsp'||u.pathname==='/index.html')u.pathname='/';if(u.pathname==='/col.jsp'&&u.searchParams.has('id')){u.pathname='/h-col-'+u.searchParams.get('id')+'.html';u.searchParams.delete('id')}if(u.searchParams.has('_reqArgs')){const data=JSON.parse(u.searchParams.get('_reqArgs'));if(data.args)data.args=Object.fromEntries(Object.entries(data.args).sort(([a],[b])=>a.localeCompare(b)));u.searchParams.set('_reqArgs',JSON.stringify(data))}}return u.href}catch{return null}}
function pageURL(u){if(!u)return false;const a=new URL(u);return a.origin===origin&&(a.pathname==='/'||/\.html$/.test(a.pathname))}
function filename(u){const a=new URL(u);if(a.pathname==='/')return a.search?'home-'+hash(u)+'.html':'index.html';return a.search?a.pathname.slice(1).replace(/\.html$/,'-page-'+hash(u)+'.html'):a.pathname.slice(1)}
async function fetchBytes(u){for(let n=0;n<3;n++)try{const r=await fetch(u,{signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('HTTP '+r.status);return Buffer.from(await r.arrayBuffer())}catch(e){if(n===2)throw e}}
async function cached(u,ext){const f=path.join(raw,hash(u)+ext);if(fs.existsSync(f))return fs.readFileSync(f);const b=await fetchBytes(u);fs.writeFileSync(f,b);return b}
function addPage(s,base){const u=norm(s,base);if(pageURL(u)&&!scheduled.has(u)){scheduled.add(u);queue.push(u)}}
function asset(s,base){const u=norm(s,base);if(!u||!/^https?:/.test(u))return;const a=new URL(u);if(!/\.(?:png|jpe?g|gif|webp|svg|avif|ico|css|js|woff2?|ttf|eot|mp4|webm)(?:$|\?)/i.test(a.pathname)&&!/(jzcusstyle|fkTheme)/.test(a.pathname))return;if(!assets.has(u)){let ext=path.extname(a.pathname);if(!/^\.[a-z0-9]{1,5}$/i.test(ext)||ext==='.jsp')ext='.css';assets.set(u,{file:'site-assets/'+hash(u)+ext})}}
function discover(t,base){for(const m of t.matchAll(/(?:https?:)?\/\/[^\s"'<>\\()]+/g))asset(m[0],base);for(const m of t.matchAll(/url\(\s*["']?([^"')]+)["']?\s*\)/g))asset(m[1],base)}
const relative=(f,t)=>path.posix.relative(path.posix.dirname(f),t)||path.posix.basename(t);
function rewriteAssets(t,u,f){return t.replace(/(?:https?:)?\/\/[^\s"'<>\\()]+/g,s=>{const a=assets.get(norm(s,u));return a?.ok?relative(f,a.file):s}).replace(/url\(\s*(["']?)([^"')]+)\1\s*\)/g,(m,q,s)=>{const a=assets.get(norm(s,u));return a?.ok?`url(${q}${relative(f,a.file)}${q})`:m})}
(async()=>{while(queue.length){const batch=queue.splice(0,4);await Promise.all(batch.map(async u=>{try{const html=(await cached(u,'.html')).toString();const dom=cheerio.load(html);pages.set(u,{file:filename(u),html,title:dom('title').text()});dom('a[href]').each((_,e)=>addPage(dom(e).attr('href'),u));for(const m of html.matchAll(/https?:\/\/(?:www\.)?yinchung\.com\/[^\s"'<>\\]*?\.html(?:\?[^\s"'<>\\]*)?/g))addPage(m[0],u);console.log('PAGE',pages.size,filename(u),dom('title').text())}catch(e){errors.push({kind:'page',url:u,error:String(e)});console.log('PAGE FAILED',u,String(e))}}))}console.log('PAGE COLLECTION COMPLETE',pages.size);
for(const [u,p]of pages)discover(p.html,u);const done=new Set();while([...assets.keys()].some(u=>!done.has(u))){const batch=[...assets.keys()].filter(u=>!done.has(u)).slice(0,10);await Promise.all(batch.map(async u=>{done.add(u);const a=assets.get(u);try{a.body=await cached(u,'.asset');a.ok=true;if(a.file.endsWith('.css'))discover(a.body.toString(),u)}catch(e){errors.push({kind:'asset',url:u,error:String(e)});console.log('ASSET FAILED',u)}}));console.log('ASSETS',done.size,'/',assets.size)}
for(const [u,a]of assets)if(a.ok)fs.writeFileSync(path.join(root,a.file),a.file.endsWith('.css')?rewriteAssets(a.body.toString(),u,a.file):a.body);
for(const [u,p]of pages){const dom=cheerio.load(rewriteAssets(p.html,u,p.file));dom('a[href]').each((_,e)=>{const el=dom(e),href=el.attr('href'),v=norm(href,u);if(pages.has(v)){el.attr('href',relative(p.file,pages.get(v).file));el.removeAttr('onclick');el.removeAttr('data-href')}else if(href.startsWith('/')&&!href.startsWith('//'))el.attr('href',new URL(href,origin).href)});dom('img[data-original]').each((_,e)=>dom(e).attr('src',dom(e).attr('data-original')));dom('head').append(`<script defer src="${relative(p.file,'site-assets/local-navigation.js')}"></script>`);let html=dom.html();for(const [v,t]of [...pages].sort((a,b)=>b[0].length-a[0].length)){if(v===origin+'/')continue;html=html.split(v).join(relative(p.file,t.file))}fs.mkdirSync(path.dirname(path.join(root,p.file)),{recursive:true});fs.writeFileSync(path.join(root,p.file),html)}
const manifest={source:origin,copiedAt:new Date().toISOString(),pages:[...pages].map(([url,p])=>({url,file:p.file,title:p.title})),assets:[...assets].filter(([,a])=>a.ok).map(([url,a])=>({url,file:a.file})),errors};fs.writeFileSync('site-copy-manifest.json',JSON.stringify(manifest,null,2));fs.writeFileSync('.gitignore','work/\n.pnpm-store/\n');console.log('COMPLETE',pages.size,'pages',manifest.assets.length,'assets',errors.length,'failures');})();
